/*
 * generated by Xtext
 */
package it.unibo.madz.mobile;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AndroidLRuntimeModule extends it.unibo.madz.mobile.AbstractAndroidLRuntimeModule {

}
