/*
* generated by Xtext
*/
package it.unibo.madz.mobile.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AndroidLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("it/unibo/madz/mobile/parser/antlr/internal/InternalAndroidL.tokens");
	}
}
