/*
 * generated by Xtext
 */
package it.unibo.madz.mobile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AndroidLUiModule extends it.unibo.madz.mobile.ui.AbstractAndroidLUiModule {
	public AndroidLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
