/*
* generated by Xtext
*/
package it.unibo.madz.mobile.ui.contentassist;

import it.unibo.madz.mobile.ui.contentassist.AbstractAndroidLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AndroidLProposalProvider extends AbstractAndroidLProposalProvider {

}
