/*
* generated by Xtext
*/
package it.unibo.madz.mobile.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class AndroidLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
