
/*
 * generated by Xtext
 */
 
package it.unibo.madz.mobile.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class AndroidLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return it.unibo.madz.mobile.ui.internal.AndroidLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return it.unibo.madz.mobile.ui.internal.AndroidLActivator.getInstance().getInjector("it.unibo.madz.mobile.AndroidL");
	}
	
}
